name: 🚀 Deploy to Stage
on:
  release:
    types:
      - published

jobs:
  deploy-stage:
    runs-on: ubuntu-latest

    steps:
      - name: Do nothing
        run: echo TODO
# TODO
# Check some other RMS project (e.g. PRIM, CustomerConnect, AccessManagement) for inspiration
