name: "📦 Update npm cache"

on:
  push:
    branches:
      - "main"

jobs:
  build-npm-cache:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read node and npm versions from package.json
        uses: skjnldsv/read-package-engines-version-actions@v3
        id: package-engines-versions

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.package-engines-versions.outputs.nodeVersion }}

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Test cache hit
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies if necessary
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci # Cache not hit, perform fresh install to build new cache
